image: registry.gitlab.info.uqam.ca/inf3135-aut2023/inf3135-aut2023-tp2/base

before_script:
  - git submodule update --init --remote --recursive
  - cd external/libtap && git checkout cmake && cd ../..

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build && cd build && cmake .. && make
  artifacts:
    paths:
      - build/*

test-unit:
  stage: test
  script:
    - cd build
    - make test
    - make test-unit

test-bats:
  stage: test
  script:
    - cd build && make test-bats
